import dns from 'node:dns';
dns.setServers(['8.8.8.8', '8.8.4.4']);
import {Outfit} from "next/font/google";

import "./globals.css";
import AppNavbar from "@/components/Navbar";
import "animate.css";
import Footer from "@/components/Footer";
import { Toaster } from 'sonner';



const OutFitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutFitFont.className} h-full antialiased`}
    >
      <body>
        <AppNavbar></AppNavbar>
        {children}
        <Toaster position="top-right" richColors />
        <Footer></Footer>
        </body>
    </html>
  );
}
