import {Outfit} from "next/font/google";
import "./globals.css";
import AppNavbar from "@/components/Navbar";
import "animate.css";
import Footer from "@/components/Footer";



const OutFitFont = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutFitFont.className} h-full antialiased`}
    >
      <body>
        <AppNavbar></AppNavbar>
        {children}
        <Footer></Footer>
        </body>
    </html>
  );
}
